# variables are defined in .env file
projects:
  campfire-event-manager:
    schema:
      - "https://niantic-social-api.nianticlabs.com/graphql":
          headers:
            Authorization: Bearer ${TOKEN}
    documents:
      - "server/campfire/queries/**/*.graphql"
      - "server/campfire/mutations/**/*.graphql"
