// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: covers.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteCoverImage = `-- name: DeleteCoverImage :execrows
DELETE FROM cover_images
WHERE cover_id = $1 AND cover_discord_user_id = $2
`

type DeleteCoverImageParams struct {
	CoverID            int64
	CoverDiscordUserID string
}

func (q *Queries) DeleteCoverImage(ctx context.Context, arg DeleteCoverImageParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCoverImage, arg.CoverID, arg.CoverDiscordUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCoverImage = `-- name: GetCoverImage :one
SELECT
    cover_id,
    cover_discord_user_id,
    cover_filename,
    cover_content_type,
    cover_data,
    cover_created_at
FROM cover_images
WHERE cover_id = $1
`

func (q *Queries) GetCoverImage(ctx context.Context, coverID int64) (CoverImage, error) {
	row := q.db.QueryRow(ctx, getCoverImage, coverID)
	var i CoverImage
	err := row.Scan(
		&i.CoverID,
		&i.CoverDiscordUserID,
		&i.CoverFilename,
		&i.CoverContentType,
		&i.CoverData,
		&i.CoverCreatedAt,
	)
	return i, err
}

const insertCoverImage = `-- name: InsertCoverImage :one
INSERT INTO cover_images (
    cover_discord_user_id,
    cover_filename,
    cover_content_type,
    cover_data
) VALUES ($1, $2, $3, $4)
RETURNING
    cover_id,
    cover_discord_user_id,
    cover_filename,
    cover_content_type,
    cover_created_at
`

type InsertCoverImageParams struct {
	CoverDiscordUserID string
	CoverFilename      string
	CoverContentType   string
	CoverData          []byte
}

type InsertCoverImageRow struct {
	CoverID            int64
	CoverDiscordUserID string
	CoverFilename      string
	CoverContentType   string
	CoverCreatedAt     pgtype.Timestamp
}

func (q *Queries) InsertCoverImage(ctx context.Context, arg InsertCoverImageParams) (InsertCoverImageRow, error) {
	row := q.db.QueryRow(ctx, insertCoverImage,
		arg.CoverDiscordUserID,
		arg.CoverFilename,
		arg.CoverContentType,
		arg.CoverData,
	)
	var i InsertCoverImageRow
	err := row.Scan(
		&i.CoverID,
		&i.CoverDiscordUserID,
		&i.CoverFilename,
		&i.CoverContentType,
		&i.CoverCreatedAt,
	)
	return i, err
}
