// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: drafts.sql

package dbsqlc

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearDraftsByClubIDs = `-- name: ClearDraftsByClubIDs :exec
DELETE FROM meetup_draft
WHERE draft_club_id = ANY($1::text[])
`

func (q *Queries) ClearDraftsByClubIDs(ctx context.Context, clubIds []string) error {
	_, err := q.db.Exec(ctx, clearDraftsByClubIDs, clubIds)
	return err
}

const createDraft = `-- name: CreateDraft :one
INSERT INTO meetup_draft (
    draft_club_id,
    draft_discord_user_id,
    draft_payload,
    draft_created_at,
    draft_updated_at
) VALUES ($1, $2, $3, $4, $5)
RETURNING
    draft_id,
    draft_club_id,
    draft_discord_user_id,
    draft_payload,
    draft_created_at,
    draft_updated_at
`

type CreateDraftParams struct {
	DraftClubID        string
	DraftDiscordUserID string
	DraftPayload       json.RawMessage
	DraftCreatedAt     pgtype.Timestamp
	DraftUpdatedAt     pgtype.Timestamp
}

type CreateDraftRow struct {
	DraftID            int64
	DraftClubID        string
	DraftDiscordUserID string
	DraftPayload       json.RawMessage
	DraftCreatedAt     pgtype.Timestamp
	DraftUpdatedAt     pgtype.Timestamp
}

func (q *Queries) CreateDraft(ctx context.Context, arg CreateDraftParams) (CreateDraftRow, error) {
	row := q.db.QueryRow(ctx, createDraft,
		arg.DraftClubID,
		arg.DraftDiscordUserID,
		arg.DraftPayload,
		arg.DraftCreatedAt,
		arg.DraftUpdatedAt,
	)
	var i CreateDraftRow
	err := row.Scan(
		&i.DraftID,
		&i.DraftClubID,
		&i.DraftDiscordUserID,
		&i.DraftPayload,
		&i.DraftCreatedAt,
		&i.DraftUpdatedAt,
	)
	return i, err
}

const deleteDraft = `-- name: DeleteDraft :execrows
DELETE FROM meetup_draft
WHERE draft_id = $1
`

func (q *Queries) DeleteDraft(ctx context.Context, draftID int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDraft, draftID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDraft = `-- name: GetDraft :one
SELECT
    d.draft_id,
    d.draft_club_id,
    d.draft_discord_user_id,
    d.draft_payload,
    d.draft_created_at,
    d.draft_updated_at,
    u.discord_user_id AS creator_id,
    u.discord_user_username AS creator_username,
    u.discord_user_display_name AS creator_display_name,
    u.discord_user_avatar_url AS creator_avatar_url
FROM meetup_draft d
LEFT JOIN discord_users u ON u.discord_user_id = d.draft_discord_user_id
WHERE d.draft_id = $1
`

type GetDraftRow struct {
	DraftID            int64
	DraftClubID        string
	DraftDiscordUserID string
	DraftPayload       json.RawMessage
	DraftCreatedAt     pgtype.Timestamp
	DraftUpdatedAt     pgtype.Timestamp
	CreatorID          pgtype.Text
	CreatorUsername    pgtype.Text
	CreatorDisplayName pgtype.Text
	CreatorAvatarUrl   pgtype.Text
}

func (q *Queries) GetDraft(ctx context.Context, draftID int64) (GetDraftRow, error) {
	row := q.db.QueryRow(ctx, getDraft, draftID)
	var i GetDraftRow
	err := row.Scan(
		&i.DraftID,
		&i.DraftClubID,
		&i.DraftDiscordUserID,
		&i.DraftPayload,
		&i.DraftCreatedAt,
		&i.DraftUpdatedAt,
		&i.CreatorID,
		&i.CreatorUsername,
		&i.CreatorDisplayName,
		&i.CreatorAvatarUrl,
	)
	return i, err
}

const listDraftsByClubIDs = `-- name: ListDraftsByClubIDs :many
SELECT
    d.draft_id,
    d.draft_club_id,
    d.draft_discord_user_id,
    d.draft_payload,
    d.draft_created_at,
    d.draft_updated_at,
    u.discord_user_id AS creator_id,
    u.discord_user_username AS creator_username,
    u.discord_user_display_name AS creator_display_name,
    u.discord_user_avatar_url AS creator_avatar_url
FROM meetup_draft d
LEFT JOIN discord_users u ON u.discord_user_id = d.draft_discord_user_id
WHERE d.draft_club_id = ANY($1::text[])
ORDER BY d.draft_created_at ASC
`

type ListDraftsByClubIDsRow struct {
	DraftID            int64
	DraftClubID        string
	DraftDiscordUserID string
	DraftPayload       json.RawMessage
	DraftCreatedAt     pgtype.Timestamp
	DraftUpdatedAt     pgtype.Timestamp
	CreatorID          pgtype.Text
	CreatorUsername    pgtype.Text
	CreatorDisplayName pgtype.Text
	CreatorAvatarUrl   pgtype.Text
}

func (q *Queries) ListDraftsByClubIDs(ctx context.Context, clubIds []string) ([]ListDraftsByClubIDsRow, error) {
	rows, err := q.db.Query(ctx, listDraftsByClubIDs, clubIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDraftsByClubIDsRow{}
	for rows.Next() {
		var i ListDraftsByClubIDsRow
		if err := rows.Scan(
			&i.DraftID,
			&i.DraftClubID,
			&i.DraftDiscordUserID,
			&i.DraftPayload,
			&i.DraftCreatedAt,
			&i.DraftUpdatedAt,
			&i.CreatorID,
			&i.CreatorUsername,
			&i.CreatorDisplayName,
			&i.CreatorAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDraft = `-- name: UpdateDraft :one
UPDATE meetup_draft
SET draft_payload = $1,
    draft_club_id = $2,
    draft_updated_at = $4
WHERE draft_id = $3
RETURNING
    draft_id,
    draft_club_id,
    draft_discord_user_id,
    draft_payload,
    draft_created_at,
    draft_updated_at
`

type UpdateDraftParams struct {
	DraftPayload   json.RawMessage
	DraftClubID    string
	DraftID        int64
	DraftUpdatedAt pgtype.Timestamp
}

type UpdateDraftRow struct {
	DraftID            int64
	DraftClubID        string
	DraftDiscordUserID string
	DraftPayload       json.RawMessage
	DraftCreatedAt     pgtype.Timestamp
	DraftUpdatedAt     pgtype.Timestamp
}

func (q *Queries) UpdateDraft(ctx context.Context, arg UpdateDraftParams) (UpdateDraftRow, error) {
	row := q.db.QueryRow(ctx, updateDraft,
		arg.DraftPayload,
		arg.DraftClubID,
		arg.DraftID,
		arg.DraftUpdatedAt,
	)
	var i UpdateDraftRow
	err := row.Scan(
		&i.DraftID,
		&i.DraftClubID,
		&i.DraftDiscordUserID,
		&i.DraftPayload,
		&i.DraftCreatedAt,
		&i.DraftUpdatedAt,
	)
	return i, err
}
