// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbsqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CoverImage struct {
	CoverID            int64
	CoverDiscordUserID string
	CoverFilename      string
	CoverContentType   string
	CoverData          []byte
	CoverCreatedAt     pgtype.Timestamp
}

type DiscordUser struct {
	DiscordUserID          string
	DiscordUserUsername    string
	DiscordUserDisplayName string
	DiscordUserAvatarUrl   string
	DiscordUserImportedAt  pgtype.Timestamp
	DiscordUserTimezone    pgtype.Text
}
