// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (
    session_id,
    session_created_at,
    session_expires_at,
    session_user_id,
    session_admin
) VALUES ($1, $2, $3, $4, $5)
`

type CreateSessionParams struct {
	SessionID        string
	SessionCreatedAt pgtype.Timestamp
	SessionExpiresAt pgtype.Timestamp
	SessionUserID    string
	SessionAdmin     bool
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.SessionID,
		arg.SessionCreatedAt,
		arg.SessionExpiresAt,
		arg.SessionUserID,
		arg.SessionAdmin,
	)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE session_expires_at < now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE session_id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, sessionID string) error {
	_, err := q.db.Exec(ctx, deleteSession, sessionID)
	return err
}

const getSessionWithUser = `-- name: GetSessionWithUser :one
SELECT
    s.session_id,
    s.session_created_at,
    s.session_expires_at,
    s.session_user_id,
    s.session_admin,
    u.discord_user_id,
    u.discord_user_username,
    u.discord_user_display_name,
    u.discord_user_avatar_url,
    u.discord_user_imported_at,
    u.discord_user_timezone
FROM sessions s
LEFT JOIN discord_users u ON s.session_user_id = u.discord_user_id
WHERE s.session_id = $1
`

type GetSessionWithUserRow struct {
	SessionID              string
	SessionCreatedAt       pgtype.Timestamp
	SessionExpiresAt       pgtype.Timestamp
	SessionUserID          string
	SessionAdmin           bool
	DiscordUserID          pgtype.Text
	DiscordUserUsername    pgtype.Text
	DiscordUserDisplayName pgtype.Text
	DiscordUserAvatarUrl   pgtype.Text
	DiscordUserImportedAt  pgtype.Timestamp
	DiscordUserTimezone    pgtype.Text
}

func (q *Queries) GetSessionWithUser(ctx context.Context, sessionID string) (GetSessionWithUserRow, error) {
	row := q.db.QueryRow(ctx, getSessionWithUser, sessionID)
	var i GetSessionWithUserRow
	err := row.Scan(
		&i.SessionID,
		&i.SessionCreatedAt,
		&i.SessionExpiresAt,
		&i.SessionUserID,
		&i.SessionAdmin,
		&i.DiscordUserID,
		&i.DiscordUserUsername,
		&i.DiscordUserDisplayName,
		&i.DiscordUserAvatarUrl,
		&i.DiscordUserImportedAt,
		&i.DiscordUserTimezone,
	)
	return i, err
}
