// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: templates.sql

package dbsqlc

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTemplateLikes = `-- name: CountTemplateLikes :one
SELECT COUNT(*)::int AS count
FROM meetup_template_likes
WHERE template_id = $1
`

func (q *Queries) CountTemplateLikes(ctx context.Context, templateID int64) (int32, error) {
	row := q.db.QueryRow(ctx, countTemplateLikes, templateID)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const createTemplate = `-- name: CreateTemplate :one
INSERT INTO meetup_templates (
    template_discord_user_id,
    template_name,
    template_payload,
    template_origin_id,
    template_synced,
    template_language,
    template_created_at,
    template_updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING
    template_id,
    template_discord_user_id,
    template_name,
    template_payload,
    template_published_at,
    template_publish_description,
    template_language,
    template_origin_id,
    template_synced,
    template_created_at,
    template_updated_at
`

type CreateTemplateParams struct {
	TemplateDiscordUserID string
	TemplateName          string
	TemplatePayload       json.RawMessage
	TemplateOriginID      pgtype.Int8
	TemplateSynced        bool
	TemplateLanguage      pgtype.Text
	TemplateCreatedAt     pgtype.Timestamp
	TemplateUpdatedAt     pgtype.Timestamp
}

type CreateTemplateRow struct {
	TemplateID                 int64
	TemplateDiscordUserID      string
	TemplateName               string
	TemplatePayload            json.RawMessage
	TemplatePublishedAt        pgtype.Timestamp
	TemplatePublishDescription pgtype.Text
	TemplateLanguage           pgtype.Text
	TemplateOriginID           pgtype.Int8
	TemplateSynced             bool
	TemplateCreatedAt          pgtype.Timestamp
	TemplateUpdatedAt          pgtype.Timestamp
}

func (q *Queries) CreateTemplate(ctx context.Context, arg CreateTemplateParams) (CreateTemplateRow, error) {
	row := q.db.QueryRow(ctx, createTemplate,
		arg.TemplateDiscordUserID,
		arg.TemplateName,
		arg.TemplatePayload,
		arg.TemplateOriginID,
		arg.TemplateSynced,
		arg.TemplateLanguage,
		arg.TemplateCreatedAt,
		arg.TemplateUpdatedAt,
	)
	var i CreateTemplateRow
	err := row.Scan(
		&i.TemplateID,
		&i.TemplateDiscordUserID,
		&i.TemplateName,
		&i.TemplatePayload,
		&i.TemplatePublishedAt,
		&i.TemplatePublishDescription,
		&i.TemplateLanguage,
		&i.TemplateOriginID,
		&i.TemplateSynced,
		&i.TemplateCreatedAt,
		&i.TemplateUpdatedAt,
	)
	return i, err
}

const deleteTemplate = `-- name: DeleteTemplate :execrows
DELETE FROM meetup_templates
WHERE template_id = $1 AND template_discord_user_id = $2
`

type DeleteTemplateParams struct {
	TemplateID            int64
	TemplateDiscordUserID string
}

func (q *Queries) DeleteTemplate(ctx context.Context, arg DeleteTemplateParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTemplate, arg.TemplateID, arg.TemplateDiscordUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getTemplateByID = `-- name: GetTemplateByID :one
SELECT
    t.template_id,
    t.template_discord_user_id,
    t.template_name,
    t.template_payload,
    t.template_published_at,
    t.template_publish_description,
    t.template_language,
    t.template_origin_id,
    t.template_synced,
    t.template_created_at,
    t.template_updated_at
FROM meetup_templates t
WHERE t.template_id = $1
`

type GetTemplateByIDRow struct {
	TemplateID                 int64
	TemplateDiscordUserID      string
	TemplateName               string
	TemplatePayload            json.RawMessage
	TemplatePublishedAt        pgtype.Timestamp
	TemplatePublishDescription pgtype.Text
	TemplateLanguage           pgtype.Text
	TemplateOriginID           pgtype.Int8
	TemplateSynced             bool
	TemplateCreatedAt          pgtype.Timestamp
	TemplateUpdatedAt          pgtype.Timestamp
}

func (q *Queries) GetTemplateByID(ctx context.Context, templateID int64) (GetTemplateByIDRow, error) {
	row := q.db.QueryRow(ctx, getTemplateByID, templateID)
	var i GetTemplateByIDRow
	err := row.Scan(
		&i.TemplateID,
		&i.TemplateDiscordUserID,
		&i.TemplateName,
		&i.TemplatePayload,
		&i.TemplatePublishedAt,
		&i.TemplatePublishDescription,
		&i.TemplateLanguage,
		&i.TemplateOriginID,
		&i.TemplateSynced,
		&i.TemplateCreatedAt,
		&i.TemplateUpdatedAt,
	)
	return i, err
}

const getTemplateForUser = `-- name: GetTemplateForUser :one
SELECT
    t.template_id,
    t.template_discord_user_id,
    t.template_name,
    t.template_payload,
    t.template_published_at,
    t.template_publish_description,
    t.template_language,
    t.template_origin_id,
    t.template_synced,
    t.template_created_at,
    t.template_updated_at,
    o.template_id AS origin_id,
    o.template_name AS origin_name,
    o.template_payload AS origin_payload,
    ou.discord_user_id AS origin_publisher_id,
    ou.discord_user_username AS origin_publisher_username,
    ou.discord_user_display_name AS origin_publisher_display_name,
    ou.discord_user_avatar_url AS origin_publisher_avatar_url
FROM meetup_templates t
LEFT JOIN meetup_templates o ON o.template_id = t.template_origin_id
LEFT JOIN discord_users ou ON ou.discord_user_id = o.template_discord_user_id
WHERE t.template_id = $1 AND t.template_discord_user_id = $2
`

type GetTemplateForUserParams struct {
	TemplateID            int64
	TemplateDiscordUserID string
}

type GetTemplateForUserRow struct {
	TemplateID                 int64
	TemplateDiscordUserID      string
	TemplateName               string
	TemplatePayload            json.RawMessage
	TemplatePublishedAt        pgtype.Timestamp
	TemplatePublishDescription pgtype.Text
	TemplateLanguage           pgtype.Text
	TemplateOriginID           pgtype.Int8
	TemplateSynced             bool
	TemplateCreatedAt          pgtype.Timestamp
	TemplateUpdatedAt          pgtype.Timestamp
	OriginID                   pgtype.Int8
	OriginName                 pgtype.Text
	OriginPayload              []byte
	OriginPublisherID          pgtype.Text
	OriginPublisherUsername    pgtype.Text
	OriginPublisherDisplayName pgtype.Text
	OriginPublisherAvatarUrl   pgtype.Text
}

func (q *Queries) GetTemplateForUser(ctx context.Context, arg GetTemplateForUserParams) (GetTemplateForUserRow, error) {
	row := q.db.QueryRow(ctx, getTemplateForUser, arg.TemplateID, arg.TemplateDiscordUserID)
	var i GetTemplateForUserRow
	err := row.Scan(
		&i.TemplateID,
		&i.TemplateDiscordUserID,
		&i.TemplateName,
		&i.TemplatePayload,
		&i.TemplatePublishedAt,
		&i.TemplatePublishDescription,
		&i.TemplateLanguage,
		&i.TemplateOriginID,
		&i.TemplateSynced,
		&i.TemplateCreatedAt,
		&i.TemplateUpdatedAt,
		&i.OriginID,
		&i.OriginName,
		&i.OriginPayload,
		&i.OriginPublisherID,
		&i.OriginPublisherUsername,
		&i.OriginPublisherDisplayName,
		&i.OriginPublisherAvatarUrl,
	)
	return i, err
}

const isTemplatePublished = `-- name: IsTemplatePublished :one
SELECT (template_published_at IS NOT NULL)::bool AS published
FROM meetup_templates
WHERE template_id = $1
`

func (q *Queries) IsTemplatePublished(ctx context.Context, templateID int64) (bool, error) {
	row := q.db.QueryRow(ctx, isTemplatePublished, templateID)
	var published bool
	err := row.Scan(&published)
	return published, err
}

const likeTemplate = `-- name: LikeTemplate :execrows
INSERT INTO meetup_template_likes (template_id, discord_user_id, liked_at)
SELECT t.template_id, $1, (now() AT TIME ZONE 'utc')
FROM meetup_templates t
WHERE t.template_id = $2 AND t.template_published_at IS NOT NULL
ON CONFLICT (template_id, discord_user_id) DO NOTHING
`

type LikeTemplateParams struct {
	UserID     string
	TemplateID int64
}

func (q *Queries) LikeTemplate(ctx context.Context, arg LikeTemplateParams) (int64, error) {
	result, err := q.db.Exec(ctx, likeTemplate, arg.UserID, arg.TemplateID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listPublishedTemplates = `-- name: ListPublishedTemplates :many
SELECT
    t.template_id,
    t.template_discord_user_id,
    t.template_name,
    t.template_payload,
    t.template_published_at,
    t.template_publish_description,
    t.template_language,
    t.template_origin_id,
    t.template_synced,
    t.template_created_at,
    t.template_updated_at,
    u.discord_user_id AS publisher_id,
    u.discord_user_username AS publisher_username,
    u.discord_user_display_name AS publisher_display_name,
    u.discord_user_avatar_url AS publisher_avatar_url,
    COALESCE((
        SELECT COUNT(*)::int FROM meetup_template_likes ml
        WHERE ml.template_id = t.template_id
    ), 0)::int AS like_count,
    (
        CASE
            WHEN $1::text IS NULL THEN FALSE
            ELSE EXISTS (
                SELECT 1 FROM meetup_template_likes ml
                WHERE ml.template_id = t.template_id
                  AND ml.discord_user_id = $1
            )
        END
    )::bool AS liked_by_me
FROM meetup_templates t
JOIN discord_users u ON u.discord_user_id = t.template_discord_user_id
WHERE t.template_published_at IS NOT NULL
  AND (
      $2::text IS NULL
      OR t.template_name ILIKE $2
      OR COALESCE(t.template_publish_description, '') ILIKE $2
  )
  AND (
      $3::text IS NULL
      OR COALESCE(t.template_payload->>'category', '') = $3
  )
  AND (
      $4::text IS NULL
      OR COALESCE(t.template_language, '') = $4
  )
  AND (
      $5::text IS NULL
      OR t.template_discord_user_id = $5
  )
  AND (
      $6::text IS NULL
      OR u.discord_user_username ILIKE $6
      OR u.discord_user_display_name ILIKE $6
  )
  AND (
      $7::text IS NULL
      OR EXISTS (
          SELECT 1 FROM meetup_template_likes vl
          WHERE vl.template_id = t.template_id
            AND vl.discord_user_id = $7
      )
  )
ORDER BY
  CASE WHEN $8::text = 'name_asc' THEN t.template_name END ASC,
  CASE WHEN $8::text = 'updated_desc' THEN t.template_updated_at END DESC,
  CASE WHEN $8::text = 'likes_desc' THEN (
      COALESCE((
          SELECT COUNT(*)::int FROM meetup_template_likes ml
          WHERE ml.template_id = t.template_id
      ), 0)
  ) END DESC,
  CASE WHEN $8::text = 'liked_desc' THEN (
      SELECT vl.liked_at FROM meetup_template_likes vl
      WHERE vl.template_id = t.template_id
        AND vl.discord_user_id = $7
  ) END DESC NULLS LAST,
  CASE WHEN $8::text IN ('published_desc', '') THEN t.template_published_at END DESC NULLS LAST,
  CASE WHEN $8::text = 'name_asc' THEN t.template_id END ASC,
  t.template_id DESC
`

type ListPublishedTemplatesParams struct {
	ViewerID    pgtype.Text
	Query       pgtype.Text
	Category    pgtype.Text
	Language    pgtype.Text
	PublisherID pgtype.Text
	Publisher   pgtype.Text
	LikedBy     pgtype.Text
	Sort        string
}

type ListPublishedTemplatesRow struct {
	TemplateID                 int64
	TemplateDiscordUserID      string
	TemplateName               string
	TemplatePayload            json.RawMessage
	TemplatePublishedAt        pgtype.Timestamp
	TemplatePublishDescription pgtype.Text
	TemplateLanguage           pgtype.Text
	TemplateOriginID           pgtype.Int8
	TemplateSynced             bool
	TemplateCreatedAt          pgtype.Timestamp
	TemplateUpdatedAt          pgtype.Timestamp
	PublisherID                string
	PublisherUsername          string
	PublisherDisplayName       string
	PublisherAvatarUrl         string
	LikeCount                  int32
	LikedByMe                  bool
}

func (q *Queries) ListPublishedTemplates(ctx context.Context, arg ListPublishedTemplatesParams) ([]ListPublishedTemplatesRow, error) {
	rows, err := q.db.Query(ctx, listPublishedTemplates,
		arg.ViewerID,
		arg.Query,
		arg.Category,
		arg.Language,
		arg.PublisherID,
		arg.Publisher,
		arg.LikedBy,
		arg.Sort,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPublishedTemplatesRow{}
	for rows.Next() {
		var i ListPublishedTemplatesRow
		if err := rows.Scan(
			&i.TemplateID,
			&i.TemplateDiscordUserID,
			&i.TemplateName,
			&i.TemplatePayload,
			&i.TemplatePublishedAt,
			&i.TemplatePublishDescription,
			&i.TemplateLanguage,
			&i.TemplateOriginID,
			&i.TemplateSynced,
			&i.TemplateCreatedAt,
			&i.TemplateUpdatedAt,
			&i.PublisherID,
			&i.PublisherUsername,
			&i.PublisherDisplayName,
			&i.PublisherAvatarUrl,
			&i.LikeCount,
			&i.LikedByMe,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplateLikers = `-- name: ListTemplateLikers :many
SELECT
    l.template_id,
    u.discord_user_id,
    u.discord_user_username,
    u.discord_user_display_name,
    u.discord_user_avatar_url
FROM meetup_template_likes l
JOIN discord_users u ON u.discord_user_id = l.discord_user_id
WHERE l.template_id = ANY($1::bigint[])
ORDER BY l.liked_at DESC, u.discord_user_username ASC
`

type ListTemplateLikersRow struct {
	TemplateID             int64
	DiscordUserID          string
	DiscordUserUsername    string
	DiscordUserDisplayName string
	DiscordUserAvatarUrl   string
}

func (q *Queries) ListTemplateLikers(ctx context.Context, templateIds []int64) ([]ListTemplateLikersRow, error) {
	rows, err := q.db.Query(ctx, listTemplateLikers, templateIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTemplateLikersRow{}
	for rows.Next() {
		var i ListTemplateLikersRow
		if err := rows.Scan(
			&i.TemplateID,
			&i.DiscordUserID,
			&i.DiscordUserUsername,
			&i.DiscordUserDisplayName,
			&i.DiscordUserAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplatesByUser = `-- name: ListTemplatesByUser :many
SELECT
    t.template_id,
    t.template_discord_user_id,
    t.template_name,
    t.template_payload,
    t.template_published_at,
    t.template_publish_description,
    t.template_language,
    t.template_origin_id,
    t.template_synced,
    t.template_created_at,
    t.template_updated_at,
    o.template_id AS origin_id,
    o.template_name AS origin_name,
    o.template_payload AS origin_payload,
    ou.discord_user_id AS origin_publisher_id,
    ou.discord_user_username AS origin_publisher_username,
    ou.discord_user_display_name AS origin_publisher_display_name,
    ou.discord_user_avatar_url AS origin_publisher_avatar_url
FROM meetup_templates t
LEFT JOIN meetup_templates o ON o.template_id = t.template_origin_id
LEFT JOIN discord_users ou ON ou.discord_user_id = o.template_discord_user_id
WHERE t.template_discord_user_id = $1
ORDER BY t.template_updated_at DESC
`

type ListTemplatesByUserRow struct {
	TemplateID                 int64
	TemplateDiscordUserID      string
	TemplateName               string
	TemplatePayload            json.RawMessage
	TemplatePublishedAt        pgtype.Timestamp
	TemplatePublishDescription pgtype.Text
	TemplateLanguage           pgtype.Text
	TemplateOriginID           pgtype.Int8
	TemplateSynced             bool
	TemplateCreatedAt          pgtype.Timestamp
	TemplateUpdatedAt          pgtype.Timestamp
	OriginID                   pgtype.Int8
	OriginName                 pgtype.Text
	OriginPayload              []byte
	OriginPublisherID          pgtype.Text
	OriginPublisherUsername    pgtype.Text
	OriginPublisherDisplayName pgtype.Text
	OriginPublisherAvatarUrl   pgtype.Text
}

func (q *Queries) ListTemplatesByUser(ctx context.Context, templateDiscordUserID string) ([]ListTemplatesByUserRow, error) {
	rows, err := q.db.Query(ctx, listTemplatesByUser, templateDiscordUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTemplatesByUserRow{}
	for rows.Next() {
		var i ListTemplatesByUserRow
		if err := rows.Scan(
			&i.TemplateID,
			&i.TemplateDiscordUserID,
			&i.TemplateName,
			&i.TemplatePayload,
			&i.TemplatePublishedAt,
			&i.TemplatePublishDescription,
			&i.TemplateLanguage,
			&i.TemplateOriginID,
			&i.TemplateSynced,
			&i.TemplateCreatedAt,
			&i.TemplateUpdatedAt,
			&i.OriginID,
			&i.OriginName,
			&i.OriginPayload,
			&i.OriginPublisherID,
			&i.OriginPublisherUsername,
			&i.OriginPublisherDisplayName,
			&i.OriginPublisherAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const publishTemplate = `-- name: PublishTemplate :one
UPDATE meetup_templates
SET template_published_at = COALESCE(template_published_at, $1),
    template_publish_description = $2,
    template_language = $3,
    template_updated_at = $1
WHERE template_id = $4 AND template_discord_user_id = $5
RETURNING
    template_id,
    template_discord_user_id,
    template_name,
    template_payload,
    template_published_at,
    template_publish_description,
    template_language,
    template_origin_id,
    template_synced,
    template_created_at,
    template_updated_at
`

type PublishTemplateParams struct {
	Now         pgtype.Timestamp
	Description pgtype.Text
	Language    pgtype.Text
	ID          int64
	UserID      string
}

type PublishTemplateRow struct {
	TemplateID                 int64
	TemplateDiscordUserID      string
	TemplateName               string
	TemplatePayload            json.RawMessage
	TemplatePublishedAt        pgtype.Timestamp
	TemplatePublishDescription pgtype.Text
	TemplateLanguage           pgtype.Text
	TemplateOriginID           pgtype.Int8
	TemplateSynced             bool
	TemplateCreatedAt          pgtype.Timestamp
	TemplateUpdatedAt          pgtype.Timestamp
}

func (q *Queries) PublishTemplate(ctx context.Context, arg PublishTemplateParams) (PublishTemplateRow, error) {
	row := q.db.QueryRow(ctx, publishTemplate,
		arg.Now,
		arg.Description,
		arg.Language,
		arg.ID,
		arg.UserID,
	)
	var i PublishTemplateRow
	err := row.Scan(
		&i.TemplateID,
		&i.TemplateDiscordUserID,
		&i.TemplateName,
		&i.TemplatePayload,
		&i.TemplatePublishedAt,
		&i.TemplatePublishDescription,
		&i.TemplateLanguage,
		&i.TemplateOriginID,
		&i.TemplateSynced,
		&i.TemplateCreatedAt,
		&i.TemplateUpdatedAt,
	)
	return i, err
}

const templateLikedByUser = `-- name: TemplateLikedByUser :one
SELECT EXISTS (
    SELECT 1 FROM meetup_template_likes
    WHERE template_id = $1 AND discord_user_id = $2
) AS liked
`

type TemplateLikedByUserParams struct {
	TemplateID    int64
	DiscordUserID string
}

func (q *Queries) TemplateLikedByUser(ctx context.Context, arg TemplateLikedByUserParams) (bool, error) {
	row := q.db.QueryRow(ctx, templateLikedByUser, arg.TemplateID, arg.DiscordUserID)
	var liked bool
	err := row.Scan(&liked)
	return liked, err
}

const unlikeTemplate = `-- name: UnlikeTemplate :exec
DELETE FROM meetup_template_likes
WHERE template_id = $1 AND discord_user_id = $2
`

type UnlikeTemplateParams struct {
	TemplateID    int64
	DiscordUserID string
}

func (q *Queries) UnlikeTemplate(ctx context.Context, arg UnlikeTemplateParams) error {
	_, err := q.db.Exec(ctx, unlikeTemplate, arg.TemplateID, arg.DiscordUserID)
	return err
}

const unpublishTemplate = `-- name: UnpublishTemplate :one
UPDATE meetup_templates
SET template_published_at = NULL,
    template_updated_at = $3
WHERE template_id = $1 AND template_discord_user_id = $2
RETURNING
    template_id,
    template_discord_user_id,
    template_name,
    template_payload,
    template_published_at,
    template_publish_description,
    template_language,
    template_origin_id,
    template_synced,
    template_created_at,
    template_updated_at
`

type UnpublishTemplateParams struct {
	TemplateID            int64
	TemplateDiscordUserID string
	TemplateUpdatedAt     pgtype.Timestamp
}

type UnpublishTemplateRow struct {
	TemplateID                 int64
	TemplateDiscordUserID      string
	TemplateName               string
	TemplatePayload            json.RawMessage
	TemplatePublishedAt        pgtype.Timestamp
	TemplatePublishDescription pgtype.Text
	TemplateLanguage           pgtype.Text
	TemplateOriginID           pgtype.Int8
	TemplateSynced             bool
	TemplateCreatedAt          pgtype.Timestamp
	TemplateUpdatedAt          pgtype.Timestamp
}

func (q *Queries) UnpublishTemplate(ctx context.Context, arg UnpublishTemplateParams) (UnpublishTemplateRow, error) {
	row := q.db.QueryRow(ctx, unpublishTemplate, arg.TemplateID, arg.TemplateDiscordUserID, arg.TemplateUpdatedAt)
	var i UnpublishTemplateRow
	err := row.Scan(
		&i.TemplateID,
		&i.TemplateDiscordUserID,
		&i.TemplateName,
		&i.TemplatePayload,
		&i.TemplatePublishedAt,
		&i.TemplatePublishDescription,
		&i.TemplateLanguage,
		&i.TemplateOriginID,
		&i.TemplateSynced,
		&i.TemplateCreatedAt,
		&i.TemplateUpdatedAt,
	)
	return i, err
}

const updateTemplate = `-- name: UpdateTemplate :one
UPDATE meetup_templates
SET template_name = $1,
    template_payload = $2,
    template_language = $3,
    template_synced = FALSE,
    template_updated_at = $6
WHERE template_id = $4 AND template_discord_user_id = $5
RETURNING
    template_id,
    template_discord_user_id,
    template_name,
    template_payload,
    template_published_at,
    template_publish_description,
    template_language,
    template_origin_id,
    template_synced,
    template_created_at,
    template_updated_at
`

type UpdateTemplateParams struct {
	TemplateName          string
	TemplatePayload       json.RawMessage
	TemplateLanguage      pgtype.Text
	TemplateID            int64
	TemplateDiscordUserID string
	TemplateUpdatedAt     pgtype.Timestamp
}

type UpdateTemplateRow struct {
	TemplateID                 int64
	TemplateDiscordUserID      string
	TemplateName               string
	TemplatePayload            json.RawMessage
	TemplatePublishedAt        pgtype.Timestamp
	TemplatePublishDescription pgtype.Text
	TemplateLanguage           pgtype.Text
	TemplateOriginID           pgtype.Int8
	TemplateSynced             bool
	TemplateCreatedAt          pgtype.Timestamp
	TemplateUpdatedAt          pgtype.Timestamp
}

func (q *Queries) UpdateTemplate(ctx context.Context, arg UpdateTemplateParams) (UpdateTemplateRow, error) {
	row := q.db.QueryRow(ctx, updateTemplate,
		arg.TemplateName,
		arg.TemplatePayload,
		arg.TemplateLanguage,
		arg.TemplateID,
		arg.TemplateDiscordUserID,
		arg.TemplateUpdatedAt,
	)
	var i UpdateTemplateRow
	err := row.Scan(
		&i.TemplateID,
		&i.TemplateDiscordUserID,
		&i.TemplateName,
		&i.TemplatePayload,
		&i.TemplatePublishedAt,
		&i.TemplatePublishDescription,
		&i.TemplateLanguage,
		&i.TemplateOriginID,
		&i.TemplateSynced,
		&i.TemplateCreatedAt,
		&i.TemplateUpdatedAt,
	)
	return i, err
}
