// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package dbsqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDiscordUser = `-- name: GetDiscordUser :one
SELECT
    discord_user_id,
    discord_user_username,
    discord_user_display_name,
    discord_user_avatar_url,
    discord_user_imported_at,
    discord_user_timezone
FROM discord_users
WHERE discord_user_id = $1
`

func (q *Queries) GetDiscordUser(ctx context.Context, discordUserID string) (DiscordUser, error) {
	row := q.db.QueryRow(ctx, getDiscordUser, discordUserID)
	var i DiscordUser
	err := row.Scan(
		&i.DiscordUserID,
		&i.DiscordUserUsername,
		&i.DiscordUserDisplayName,
		&i.DiscordUserAvatarUrl,
		&i.DiscordUserImportedAt,
		&i.DiscordUserTimezone,
	)
	return i, err
}

const setDiscordUserTimeZone = `-- name: SetDiscordUserTimeZone :execrows
UPDATE discord_users
SET discord_user_timezone = $2
WHERE discord_user_id = $1
`

type SetDiscordUserTimeZoneParams struct {
	DiscordUserID       string
	DiscordUserTimezone pgtype.Text
}

func (q *Queries) SetDiscordUserTimeZone(ctx context.Context, arg SetDiscordUserTimeZoneParams) (int64, error) {
	result, err := q.db.Exec(ctx, setDiscordUserTimeZone, arg.DiscordUserID, arg.DiscordUserTimezone)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertDiscordUser = `-- name: UpsertDiscordUser :exec
INSERT INTO discord_users (
    discord_user_id,
    discord_user_username,
    discord_user_display_name,
    discord_user_avatar_url
) VALUES ($1, $2, $3, $4)
ON CONFLICT (discord_user_id) DO UPDATE
SET discord_user_username     = EXCLUDED.discord_user_username,
    discord_user_display_name = EXCLUDED.discord_user_display_name,
    discord_user_avatar_url   = EXCLUDED.discord_user_avatar_url,
    discord_user_imported_at  = now()
`

type UpsertDiscordUserParams struct {
	DiscordUserID          string
	DiscordUserUsername    string
	DiscordUserDisplayName string
	DiscordUserAvatarUrl   string
}

func (q *Queries) UpsertDiscordUser(ctx context.Context, arg UpsertDiscordUserParams) error {
	_, err := q.db.Exec(ctx, upsertDiscordUser,
		arg.DiscordUserID,
		arg.DiscordUserUsername,
		arg.DiscordUserDisplayName,
		arg.DiscordUserAvatarUrl,
	)
	return err
}
